- name: add docker repository
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: install docker packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
    - containerd.io
#    - containernetworking-plugins

- name: enable containerd service
  ansible.builtin.systemd:
    name: containerd
    enabled: yes

- name: deploy containerd config
  ansible.builtin.template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
  notify: restart containerd
