- name: create YUM repo configuration
  ansible.builtin.yum_repository:
    name: kubernetes
    description: Kubernetes repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    exclude: kubelet kubeadm kubectl

- name: install k8s packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  loop:
    - kubelet
    - kubectl
    - kubeadm

- name: enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: yes

- name: pull in Calico plugin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.25.1/manifests/calico.yaml
    dest: ~/calico.yaml

- name: install Calico CNI
  kubernetes.core.k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    src: ~/calico.yaml
